on:
  push:
    branches: main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: 🔨 Build Project
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: 📂 Sync files to public_html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/ # Ensure this is the correct path to the built frontend
          server-dir: /public_html/ # Upload directly to public_html
          dangerous-clean-slate: true # Clears existing files to prevent conflicts
